// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TokensResponse tokens response
//
// swagger:model TokensResponse
type TokensResponse struct {

	// access token
	AccessToken string `json:"access_token"`

	// refresh token
	RefreshToken string `json:"refresh_token"`
}

// Validate validates this tokens response
func (m *TokensResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tokens response based on context it is used
func (m *TokensResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TokensResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TokensResponse) UnmarshalBinary(b []byte) error {
	var res TokensResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
