swagger: "2.0"
info:
  description: Pharmacy
  title: Pharmacy
  version: 1.0.0
consumes:
  - application/io.goswagger.examples.todo-list.v1+json
produces:
  - application/io.goswagger.examples.todo-list.v1+json
schemes:
  - http
tags:
  - name: payments
    description: Payments
  - name: user
    description: User of system
  - name: report
    description: report
paths:
  /user/login:
    post:
      tags:
        - user
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserLoginRequest'
      responses:
        200:
          description: login success
          schema:
            $ref: '#/definitions/BaseResponse'
        401:
          description: failed to authorize
          schema:
            $ref: '#/definitions/BaseResponse'
        500:
          description: internal server error
          schema:
            $ref: '#/definitions/BaseResponse'
  /user/refresh:
    post:
      tags:
        - user
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserRefreshRequest'
      responses:
        200:
          description: refresh success
          schema:
            $ref: '#/definitions/BaseResponse'
        401:
          description: failed to refresh
          schema:
            $ref: '#/definitions/BaseResponse'
        500:
          description: internal server error
          schema:
            $ref: '#/definitions/BaseResponse'


definitions:
  BaseResponse:
    type: object
    properties:
      error:
        type: string
        x-omitempty: false
      success:
        type: boolean
        x-omitempty: false

  UserLoginRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        minLength: 8

  UserRefreshRequest:
    type: object
    required:
      - token
    properties:
      token:
        type: string