swagger: "2.0"
info:
  description: Pharmacy
  title: Pharmacy
  version: 1.0.0
consumes:
  - application/io.goswagger.examples.todo-list.v1+json
produces:
  - application/io.goswagger.examples.todo-list.v1+json
schemes:
  - http
tags:
  - name: payments
    description: Payments
  - name: user
    description: User of system
  - name: report
    description: report
paths:
  /health: # TODO delete when other endpoints appear
    post:
      tags:
        - payments
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/BaseResponse'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/BaseResponse'
        400:
          description: Failed
          schema:
            $ref: '#/definitions/BaseResponse'

  /user/login:
    post:
      tags:
        - user
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserLoginRequest'
      responses:
        200:
          description: login success
          schema:
            $ref: '#/definitions/UserLoginResponse'
        401:
          description: failed to authorize
          schema:
            $ref: '#/definitions/BaseResponse'
        500:
          description: internal server error
          schema:
            $ref: '#/definitions/BaseResponse'
  /user/refresh:


definitions:
  BaseResponse:
    type: object
    properties:
      error:
        type: string
        x-omitempty: false
      success:
        type: boolean
        x-omitempty: false

  UserLoginRequest:
    type: object
    properties:
      email:
        type: string
      password:
        type: string

  UserLoginResponse:
    type: object
    properties:
      token:
        type: string
      refresh_token:
        type: string
